apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
  {{- with .Values.tags }}
    first: {{ .machine }}
  {{- end }}
data:
  myvalue: "Sample Config Map"
  state: {{ .Values.state }}
  zone: {{ quote .Values.infra.zone }}
  region: {{ quote .Values.infra.region }}
  city: {{ upper .Values.city }}
  {{ if eq .Values.infra.region "us-east" }}available: true {{ end }}
  {{ if eq .Values.infra.region "us-west" }}western-zone: true {{ end }}
  {{- $relname := .Release.Name -}}
  {{- with .Values.tags }}
  Machine Type: {{ .machine | default "NA" | quote }}
  Rack ID: {{ .rack | quote }}
  Storage Type: {{ .drive | upper | quote }}
  Size: {{ .size | quote }}
  Release: {{ $relname }}
  {{- end }}
  lang-support: |-
  {{- range $index, $lang := .Values.languages }}
    - {{ $index }} : {{ $lang | title | quote }}
  {{- end }}