apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  myvalue: "Sample Config Map"
  state: {{ .Values.state }}
  zone: {{ quote .Values.infra.zone }}
  region: {{ quote .Values.infra.region }}
  city: {{ upper .Values.city }}
  {{ if eq .Values.infra.region "us-east" }}available: true {{ end }}
  {{ if eq .Values.infra.region "us-west" }}western-zone: true {{ end }}